include:
  - project: acid-tango/gitlab/pipelines
    ref: master
    file: renovate/renovate.yaml

stages:
  - test
  - renovate

test:
  stage: test
  needs: []
  image: node:12-alpine
  except:
    - schedules
  script:
    - npm ci
    - npm run lint
    - npm test

renovate:
  stage: renovate
  needs: []
  extends: .renovate-template
